### ISSUE TITLE
Improve the changing of font sizes

### ISSUE THREAD

**Issue by Almost-Senseless-Coder** [Almost-Senseless-Tech/Voskle-Live-Transcribe#9]
Right now, the font sizes are provided in `em`, which doesn't work as well as we thought it would.

I instead propose using sizes in `sp`, something like 18, 24, 30, 36 and 42 `sp`, mapped to the text values normal, larger, large, very large and largest.

As the font size increases, so should the line height to maintain proper readability.

Additionally, a zoom factor of up to 200% should not break the UI.

@RavioliRanger I'd appreciate if you could look into this, since it's more of a visual issue.

**Comment by RavioliRanger** [comment]
Opened new branch and started working on it.
WIP: Changed font scaling from .em to .sp
